language: scala

scala:
   - 2.12.1

sudo: false

jdk:
   - oraclejdk8

script:
   - sbt ++$TRAVIS_SCALA_VERSION test dist

scripts:
# Tricks to avoid unnecessary cache updates, from
# http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

deploy:
  provider: script
  skip_cleanup: true
  script: ./scripts/deploy-to-gh-pages.sh
  on:
    branch: master